insert into user values (99999999, 'Kassai út 26', 'Debrecen', 'uniuser@unidress.hu', 'Micura', 'Adam', '$2a$10$.KYlOUY9IpPpDE.4wOmweuj5aAUS3MtnhLHPIyG3oxrHNfDuUuxNG', '36304525789',4116, 'uniuser');

insert into role values (1, 'ADMIN');
insert into users_roles values (99999999, 1);

INSERT INTO category VALUES (1,'Polók', 'tshirts_category.jpg');
INSERT INTO category VALUES (2,'Farmerek', 'farmers_category.jpg');
INSERT INTO category VALUES (3,'Felsők', 'tops_category.jpg');
INSERT INTO category VALUES (4,'Cipők', 'shoes_category.jpg');

insert into product values (1, 2850,  'white', 'UniShirt póló 100% polyester Los Angeles 163g/m2 - AquaFX nedvszívó képesség - Freshcare mikrobaölő tulajdonság','empty_product.jpg', 'UniShirt 1', 'Raktáron', 1);
insert into product values (2, 3220,  'white', 'UniShirt póló 100% polyester Los Angeles 163g/m2 - AquaFX nedvszívó képesség - Freshcare mikrobaölő tulajdonság','empty_product.jpg', 'UniShirt 2', 'Raktáron', 1);
insert into product values (3, 5220,  'black', 'UniShirt póló 100% polyester Los Angeles 163g/m2 - AquaFX nedvszívó képesség - Freshcare mikrobaölő tulajdonság','empty_product.jpg', 'UniShirt 3', 'Raktáron', 1);
insert into product values (4, 2120,  'blue', 'UniShirt póló 100% polyester Los Angeles 163g/m2 - AquaFX nedvszívó képesség - Freshcare mikrobaölő tulajdonság','empty_product.jpg', 'UniShirt 4', 'Raktáron', 1);
insert into product values (5, 4250,  'yellow', 'UniFarmer póló 100% polyester','empty_product.jpg', 'UniFarmer 1', 'Raktáron', 2);
insert into product values (6, 3200,  'white', 'UniFarmer póló 100% polyester San Francisco','empty_product.jpg', 'UniFarmer 2', 'Raktáron', 2);
insert into product values (7, 7200,  'blue', 'UniFarmer póló 100% polyester Los Angeles','empty_product.jpg', 'UniFarmer 3', 'Raktáron', 2);
insert into product values (8, 6999,  'black', 'UniFarmer póló 100% polyester Las Vegas','empty_product.jpg', 'UniFarmer 4', 'Raktáron', 2);
insert into product values (9, 9999,  'white', 'UniTop póló 100% polyester New York','empty_product.jpg', 'UniTop 1', 'Raktáron', 3);
insert into product values (10, 11999,  'white', 'UniTop póló 100% polyester San Francisco','empty_product.jpg', 'UniTop 2', 'Raktáron', 3);
insert into product values (11, 13599,  'blue', 'UniTop póló 100% polyester Los Angeles','empty_product.jpg', 'UniTop 3', 'Raktáron', 3);
insert into product values (12, 17000,  'pink', 'UniTop póló 100% polyester Las Vegas','empty_product.jpg', 'UniTop 4', 'Raktáron', 3);
insert into product values (13, 31899,  'white', 'UniShoes cipő 100% bőr','empty_product.jpg', 'UniShoes 1', 'Raktáron', 4);
insert into product values (14, 19999,  'gray', 'UniShoes cipő 100% bőr','empty_product.jpg', 'UniShoes 2', 'Raktáron', 4);
insert into product values (15, 32200,  'blue', 'UniShoes cipő 100% bőr','empty_product.jpg', 'UniShoes 3', 'Raktáron', 4);

insert into size values (1, 'S');
insert into size values (2, 'M');
insert into size values (3, 'L');
insert into size values (4, 'XL');
insert into size values (5, '39');
insert into size values (6, '40');
insert into size values (7, '41');
insert into size values (8, '42');

insert into product_sizes values(1, 1);
insert into product_sizes values(1, 2);
insert into product_sizes values(1, 3);
insert into product_sizes values(1, 4);
insert into product_sizes values(2, 1);
insert into product_sizes values(2, 2);
insert into product_sizes values(3, 3);
insert into product_sizes values(4, 4);
insert into product_sizes values(3, 1);
insert into product_sizes values(3, 2);
insert into product_sizes values(4, 1);
insert into product_sizes values(4, 2);
insert into product_sizes values(4, 3);
insert into product_sizes values(5, 1);
insert into product_sizes values(5, 2);
insert into product_sizes values(5, 3);
insert into product_sizes values(5, 4);
insert into product_sizes values(6, 1);
insert into product_sizes values(7, 1);
insert into product_sizes values(7, 2);
insert into product_sizes values(7, 3);
insert into product_sizes values(7, 4);
insert into product_sizes values(8, 1);
insert into product_sizes values(8, 2);
insert into product_sizes values(8, 3);
insert into product_sizes values(9, 1);
insert into product_sizes values(9, 2);
insert into product_sizes values(10, 1);
insert into product_sizes values(10, 2);
insert into product_sizes values(10, 3);
insert into product_sizes values(10, 4);
insert into product_sizes values(11, 1);
insert into product_sizes values(11, 2);
insert into product_sizes values(11, 3);
insert into product_sizes values(12, 1);
insert into product_sizes values(12, 2);
insert into product_sizes values(12, 3);
insert into product_sizes values(12, 4);
insert into product_sizes values(13, 6);
insert into product_sizes values(13, 7);
insert into product_sizes values(13, 8);
insert into product_sizes values(14, 5);
insert into product_sizes values(14, 6);
insert into product_sizes values(14, 8);
insert into product_sizes values(15, 5);
insert into product_sizes values(15, 6);
insert into product_sizes values(15, 7);
insert into product_sizes values(15, 8);